# Generated by Django 2.2.16 on 2022-03-23 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211107_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True,
                                              validators=[django.core.validators.MinValueValidator(0),
                                                          django.core.validators.MaxValueValidator(2022)], 
                                              verbose_name='Год выпуска'),
        ),
    ]
